services:
  app:
    image: wynneve/laravel-task:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nginx

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro